services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
  postgresql:
    image: postgres:13.4-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api-pwd
      - POSTGRES_DB=api
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./api/docker-scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
volumes:
  database-data: {}
