CREATE TABLE IF NOT EXISTS login_user(
  LOGIN VARCHAR(100) PRIMARY KEY NOT NULL,
  PASSWORD VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS matches(
  ID SERIAL PRIMARY KEY NOT NULL,
  MATCH_ID VARCHAR(50),
  REGISTERED_ON TIMESTAMPTZ NOT NULL,
  GAME_OVER BOOLEAN,
  PLAYER_X VARCHAR(100),
  PLAYER_Y VARCHAR(100),
  WINNER VARCHAR(100),
  CONSTRAINT fk_player_x
    FOREIGN KEY (PLAYER_X)
    REFERENCES login_user (LOGIN)
    ON DELETE SET NULL,
  CONSTRAINT fk_player_y
    FOREIGN KEY (PLAYER_Y)
    REFERENCES login_user (LOGIN)
    ON DELETE SET NULL
);
